version: '2'
services:

  database:
    image: slydetector/simply-Newzflash-mariadb
    restart: unless-stopped
    volumes:
      - $PWD/data/var_lib_mysql:/var/lib/mysql
      - $PWD/data/etc_mysql_conf.d:/etc/mysql/conf.d
      - $PWD/data/mysql_user:/mysql_user
    environment:
      - MYSQL_ROOT_PASSWORD=Newzflash
      - MYSQL_DATABASE=Newzflash
      - MYSQL_USER=Newzflash
      - MYSQL_PASSWORD=Newzflash
    expose:
      - "3306"

  newzflash:
    image: demetryromanowski/newzflash-docker
    restart: unless-stopped
    ports:
      - 80:80
    env_file: 
      - $PWD/etc/newzflash.conf
    volumes:
      - $PWD/data/covers:/var/www/Newzflash/resources/covers/
      - $PWD/data/nzb:/var/www/Newzflash/resources/nzb/
      - $PWD/data/tmp:/var/www/Newzflash/resources/tmp/unrar/
      # configuration/ is expected to contain
      #  - config.php
      #  - ircscraper_settings.php
      #  - settings.php
      #  - install.lock (only after setup has completed)
      - $PWD/data/configuration:/var/www/Newzflash/configuration/
      - $PWD/data/log/nginx-error.log:/var/log/nginx/nginx-error.log
      - $PWD/data/log/nginx-access.log:/var/log/nginx/access.log
      - $PWD/data/log/php-fpm.log:/var/log/php-fpm.log
      - $PWD/data/log/php_errors.log:/var/www/Newzflash/resources/logs/php_errors.log
      - $PWD/data/log/php_errors_web.log:/var/www/Newzflash/resources/logs/php_errors_web.log
      - $PWD/data/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/data/mytop:/root/.mytop
      - $PWD/data/predb_progress.txt:/var/www/Newzflash/cli/data/predb_progress.txt
      - $PWD/data/import:/var/www/Newzflash/resources/import/
      - $PWD/data/proxychains.conf:/etc/proxychains/proxychains.conf
      - $PWD/data/db_backups:/db_backups

  adminer:
    image: clue/adminer
    restart: unless-stopped
    ports: 
      - 8880:8880

  redis:
    image: redis:3.2.6-alpine
    restart: unless-stopped
